
services:
  app:
    build: .
    environment:
      PORT: 8000
      DRIVER: "mysql"
      ADDRESS: "database-1.c0bfrau4r4jh.ap-southeast-1.rds.amazonaws.com"
      DB_PORT: 3306
      USERNAME: "admin"
      PASSWORD: "group1be6"
      NAME: "group1"
    restart: always
    ports:
      - 8081:8000
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080