name: remote ssh command
on: 
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          if [ -d "BE" ]; then
            docker-compose down --rmi all
            rm -rf "BE"
          fi
          git clone https://github.com/e-commerce-group-1/BE.git
          cd BE
          docker-compose up --build -d
